export const SET_SOCKET = 'set_socket';
export const SET_DROPPED = 'set_dropped';
export const SET_ACTIVE_GROUP_USER = 'set_active_group_user';
export const SET_ACTIVE_ROOM = 'set_active_room';
export const SET_USER_GATHER = 'set_user_gather';
export const SET_FRIEND_GATHER = 'set_friend_gather';
export const SET_GROUP_GATHER = 'set_group_gather';
export const ADD_GROUP_MESSAGE = 'add_group_message';
export const SET_GROUP_MESSAGES = 'set_group_messages';
export const ADD_FRIEND_MESSAGE = 'add_friend_message';
export const SET_FRIEND_MESSAGES = 'set_friend_messages';
export const DEL_GROUP = 'del_group';
export const DEL_FRIEND = 'del_friend';
export const ADD_UNREAD_GATHER = 'set_unread_gather';
export const LOSE_UNREAD_GATHER = 'lose_unread_gather';
export const SET_GROUP_ALL_USER = 'set_group_all_user'; //设置群聊所有成员的数据--axiszql
export const SET_GROUP_ONLINE_USER_COUNT = 'set_group_online_user_count';
export const DEAL_FRIEND_OFF = 'deal_friend_off'; //处理好友下线事件
export const DEAL_FRIEND_ON = 'deal_friend_on'; //处理好友上线事件
export const SET_FRIEND_SHOW_MSG = 'set_friend_show_msg'; // 设置当前用户已经显示的发送消息
export const SET_GROUP_SHOW_MSG = 'set_group_show_msg';
